language: java

jdk:
  - oraclejdk8

before_install:
  - sudo sudo apt-get --only-upgrade install gradle -f
  - gradle -v

install:
  - gradle clean check

script:
  - gradle test jacocoTestReport install