language: java

jdk:
  - oraclejdk8

before_install:
  - sudo add-apt-repository ppa:cwchien/gradle
  - sudo apt-get update
  - sudo apt-get install gradle
  - gradle -v

install:
  - gradle clean check

script:
  - gradle test jacocoTestReport install