language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update && sudo apt-get upgrade gradle -y
  - gradle -v

install:
  - gradle clean check

script:
  - gradle test jacocoTestReport install